/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;

import static org.junit.Assert.*;

import java.util.List;

import org.junit.After;
import org.junit.Assert;
import org.junit.Before;


public class LibraryTest {
    
	
	WebDriver driver;
	
	@Before
	public void openBrowser()
	{
		driver = new ChromeDriver();
	}
	
	@Test 
    public void testSomeLibraryMethod() {
        WebDriver driver = new ChromeDriver();
        driver.get("https://en.wikipedia.org/wiki/Main_Page");
        WebElement barreRecherche = driver.findElement(By.id("searchInput"));
        barreRecherche.sendKeys("World cup");
        WebElement button = driver.findElement(By.id("searchButton"));
        button.click();
        WebElement link = driver.findElement(By.xpath("/html/body/div[3]/div[3]/div[4]/div/p[1]/a"));  
        link.click();
        WebElement titre = driver.findElement(By.id("firstHeading"));
        Assert.assertEquals("FIFA World Cup", titre.getText());
    }
	
	
	@After
	public void closeBrowser()
	{
		driver.quit();
	}

	
}
